w5d1/Redditclone/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
  end
  resources :subs, except: [:destroy]
  resources :posts, except: [:index]

end

w5d1/Redditclone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author, presence: true
  validate :atleast_one_sub

  def atleast_one_sub
    self.subs.length >= 1
  end

  has_many :postsubs,
  foreign_key: :post_id,
  dependent: :destroy,
  inverse_of: :post

  has_many :subs, through: :postsubs

  belongs_to :author,
  foreign_key: :author_id,
  class_name: "User"

end

w5d1/Redditclone/app/models/postsub.rb
# == Schema Information
#
# Table name: postsubs
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Postsub < ActiveRecord::Base
  validates :post, :sub, presence: true
  validates :post_id, uniqueness: { scope: :sub_id }
  

  belongs_to :post, foreign_key: :post_id

  belongs_to :sub, foreign_key: :sub_id
end

w5d1/Redditclone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true

  belongs_to :moderator,
  foreign_key: :moderator_id,
  class_name: "User"

  has_many :posts, through: :postsubs

  has_many :postsubs,
  foreign_key: :sub_id,
  dependent: :destroy,
  inverse_of: :sub

end

w5d1/Redditclone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :subs,
  foreign_key: :moderator_id,
  class_name: "Sub"

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(128)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
end

w5d1/Redditclone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

end

w5d1/Redditclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_author?, only: [:edit, :update]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:messages] = ["invalid post"]
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:messages] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to subs_url(@post.subs.first)
  end

  def show
    @post = Post.find_by(id: params[:id])
    render :show
  end

  def is_author?
    current_user.id == Post.find_by(id: params[:id]).author_id
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
  end

end

w5d1/Redditclone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to user_url(current_user)
    else
      render :new
    end
  end

  def create
    @user = User.find_by_credentials(session_params[:username], session_params[:password])
    if @user
      login(@user)
      flash[:messages] = ["Welcome!"]
      redirect_to user_url(@user)
    else
      render :new
      flash.now[:messages] = ["Invalid loggin"]
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

  private

  def session_params
    params.require(:user).permit(:username, :password)
  end

end

w5d1/Redditclone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :is_moderator?, only: [:edit, :update]

  def is_moderator?
    current_user.id == Sub.find_by(id: params[:id]).moderator_id
  end

  def new
    @sub = Sub.new
    @sub.moderator_id = current_user.id
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:message] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:message] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def index
    render :index
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :moderator_id, :description)
  end

end

w5d1/Redditclone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:message] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

w5d1/Redditclone/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\'#{form_authenticity_token}\'>".html_safe
  end
end

w5d1/Redditclone/app/helpers/posts_helper.rb
module PostsHelper
end

w5d1/Redditclone/app/helpers/sessions_helper.rb
module SessionsHelper
end

w5d1/Redditclone/app/helpers/subs_helper.rb
module SubsHelper
end

w5d1/Redditclone/app/helpers/users_helper.rb
module UsersHelper
end

w5d1/Redditclone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redditclone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <div>
    <% if current_user %>
    <%= link_to "Log out", session_url, method: :delete%>
    <% else %>
    <%= link_to "Sign up", new_user_url %>
    <%= link_to "Log in", new_session_url %>
    <% end %>
  </div>
</head>

<body>

<%= yield %>

</body>
</html>

w5d1/Redditclone/app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>
<% title = post.persisted? ?  "Edit Post" : "New Post" %>

<h1> <%= title %> </h1>

<form action=" <%= action_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value=" <%= http_method %>">

  <label for="title"> Title </label>
  <input type="text" name="post[title]" value=" <%= post.title %>">

  <br>

  <label for="url"> Url </label>
  <input type="text" name="post[url]" value=" <%= post.url %>">

  <br>

  <label for="content"> Content </label>
  <textarea name="post[content]" rows="20" cols="80"> <%= post.content %> </textarea>

  <br>

  <label for="sub_id"> Subreddits </label>

  <input type="hidden" name="post[sub_ids][]" value="">


  <% Sub.all.each do |sub| %>
  <label for="sub_id"> <%= sub.title %>
  <input id = "sub_id"
         type="checkbox"
         name="post[sub_ids][]"
         value="<%= sub.id %>"
         <%= "checked" if post.sub_ids.include?(sub.id) %>>
  </label>
  <% end %>

  <br>

  <input type="submit">

</form>

w5d1/Redditclone/app/views/posts/edit.html.erb
<!-- edit post -->
<%= render "form", post: @post %>

w5d1/Redditclone/app/views/posts/new.html.erb
<!-- new post -->

<%= render "form", post: @post %>

w5d1/Redditclone/app/views/posts/show.html.erb
<!-- post -->

<h1><a href=" http://<%=@post.url%> "> <%= @post.title %></a></h1>

<p> <%= @post.content %></p>

<%= link_to "Edit post", edit_post_url(@post) %>

w5d1/Redditclone/app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% http_method = sub.persisted? ? "PATCH" : "POST" %>
<% title = sub.persisted? ?  "Edit Sub" : "New Sub" %>

<h1> <%= title %> </h1>

<form action=" <%= action_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value=" <%= http_method %>">

  <label for="title"> Title </label>
  <input type="text" name="sub[title]" value=" <%= sub.title %>">

  <label for="description"> Description </label>
  <textarea name="sub[description]" rows="20" cols="80"> <%= sub.description %> </textarea>

  <input type="submit">

</form>

w5d1/Redditclone/app/views/subs/edit.html.erb
<!-- edit sub -->
<%= render "form", sub: @sub %>

w5d1/Redditclone/app/views/subs/index.html.erb
<!-- list all subs -->
<h1>List of Subreddits</h1>
<ul>
<% Sub.all.each do |sub| %>
<li><%= link_to "#{sub.title}", sub_url(sub) %></li>
<% end  %>
</ul>

w5d1/Redditclone/app/views/subs/new.html.erb
<!-- new sub -->
<%= render "form", sub: @sub %>

w5d1/Redditclone/app/views/subs/show.html.erb
<!-- display posts for given sub -->
<h1><%= @sub.title %></h1>
<ul>
<% @sub.posts.all.each do |post| %>
<li><%= link_to "#{post.title}", post_url(post) %></li>
<% end  %>
</ul>

w5d1/Redditclone/app/views/users/new.html.erb
<!-- signup -->
<h1>New user</h1>

<form action=" <%= users_url %>" method="post">
  <%= auth_token %>
  <h1>Sign up!</h1>

  <label for="username">Username:</label>
  <input type="text" name="user[username]">

  <label for="password">Password (must be at least 6 characters):</label>
  <input type="password" name="user[password]">

  <input type="submit" value="Create User">
</form>

w5d1/Redditclone/app/views/users/show.html.erb
<!-- user page -->
<h1>Welcome <%= current_user.username %>!</h1>

<!-- content -->